image: node:latest

stages:
  - deploy

variables:
  GIT_DEPTH: 1

pages:
  stage: deploy

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - .dockerignore
        - .editorconfig
        - .gitattributes
        - .github/*
        - .gitignore
        - aide_de_camp.py
        - assets/fonts/*.txt
        - Dockerfile
        - LICENSE
        - README.md
      when: never

  script:
    - npm install
    - npx sass --no-source-map assets
    - npx @11ty/eleventy --output='public' --pathprefix="$CI_PROJECT_NAME"
    # GitLab Pages only publish files in this folder

  artifacts:
    paths:
      - public
