name: build 11ty site

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .dockerignore
      - .editorconfig
      - .gitattributes
      - .github/workflows/docker.yml
      - .gitignore
      - .gitlab-ci.yml
      - aide_de_camp.py
      - assets/fonts/*.txt
      - Dockerfile
      - LICENSE
      - README.md

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 # dont use cache coz ignore package-lock.json
        with:
          node-version: "latest"
      - name: Install dependencies & build
        # dont use `npm ci` coz ignore package-lock.json
        run: |
          npm install
          npx sass --no-source-map assets
          npx @11ty/eleventy --pathprefix "${{ github.event.repository.name }}"
      - uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
